name: GOSCreate

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Create GOSZip
        uses: juankaram/archive-action@v1.0.0
        with:
          args: "zip -r gosout.zip instance"
